### ISSUE TITLE
TileLayer plugin does not run with QGIS 2.16.0

### ISSUE THREAD

**Issue by Andre-J** [minorua/TileLayerPlugin#20]
After updating to QGIS 2.16.0, and selecting a layer from my list, I get this error:

Traceback (most recent call last):
			  File "C:/Users/<username>/.qgis2/python/plugins\TileLayerPlugin\tilelayerplugin.py", line 128, in run
			    self.addTileLayer(layerdef, creditVisibility)
			  File "C:/Users/<username>/.qgis2/python/plugins\TileLayerPlugin\tilelayerplugin.py", line 113, in addTileLayer
			    layer = TileLayer(self, layerdef, creditVisibility)
			  File "C:/Users/<username>/.qgis2/python/plugins\TileLayerPlugin\tilelayer.py", line 97, in __init__
			    self.userAgent = "QGIS/{0} TileLayerPlugin/{1}".format(QGis.QGIS_VERSION, self.plugin.VERSION)   # will be overwritten in QgsNetworkAccessManager::createRequest() since 2.2
			UnicodeEncodeError: 'ascii' codec can't encode character u'\xf8' in position 8: ordinal not in range(128)

Tested on Windows 8.1, OSGEO4W64 version of QGIS 2.16.0. Similar error messages appear with Ubuntu Xenial and Linux Mint. Up to QGIS 2.14.3, the plugin (still) works fine.

**Comment by minorua** [comment]
Thanks for the report.

**Comment by Andre-J** [comment]
Now working as expected. Please update the code in the official plugin repository as well soon.

**Comment by mclaeysb** [comment]
Very sad that TileLayer does not run with 2.16.0. Any chance this can get fixed again?
