### ISSUE TITLE
Any way to adjust transparency, hue, saturation, etc.?

### ISSUE THREAD

**Issue by fasiha** [minorua/TileLayerPlugin#32]
It would be great if it were possible to adjust the transparency, and other color aspects like contrast, brightness, gamma, hue, saturation, etc., in QGIS.

(Note this is different from #24, which deals with transparency in the raw tile PNGs. This issue is about rendering the tiles in QGIS.)

**Comment by minorua** [comment]
QGIS supports XYZ tile natively since 2.18 and there are various styling options in layer properties dialog. Please use it.
http://qgis.org/ja/site/forusers/visualchangelog218/index.html?highlight=xyz#feature-native-support-of-xyz-tile-layers

**Comment by fasiha** [comment]
Thanks to your plugin documentation, I realized that there were two different formats of XYZ tiles, here controlled by `yOriginTop`, and I was able to to find that QGIS 2.18 supports both too ([reference](https://issues.qgis.org/issues/16586))! So thank you for your plugin's documentation, even though I’m using the built-in QGIS tool 🤗!
